partners:
  mary: 
    name: Mary Stufflebeam
    url: http://www.facebook.com/marystufflebeam/
  andre: 
    name: Andr&eacute; Crabb
    url: http://andrecrabb.com/
  hayg: 
    name: Hayg Astourian
    url: http://www.facebook.com/hayg.astourian
  josh: 
    name: Joshua Hawn
    url: http://www.facebook.com/joshua.hawn

permalink: pretty
markdown: kramdown
future: false
server: true
auto: true
