partners:
  mary: <a href="http://www.facebook.com/marystufflebeam">Mary Stufflebeam</a>
  andre: <a href="http://www.linkedin.com/pub/andr%C3%A9-crabb/32/925/193">Andr&eacute; Crabb</a>

permalink: pretty
