partners:
  mary:
    name: Mary Stufflebeam
    url: https://www.linkedin.com/in/stufflebear
  andre:
    name: Andr&eacute; Crabb
    url: http://andrecrabb.com/
  hayg:
    name: Hayg Astourian
    url: https://security.stackexchange.com/users/23976/returneax
  josh:
    name: Joshua Hawn
    url: http://www.facebook.com/joshua.hawn
  molly:
    name: Molly Raven
    url: http://www.mollyraven.com

source: _source
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rogue

future: false
exclude:
  - _assets/stylesheets/fontcustom/*
  - vendor

assets:
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/bower
    - _assets/webpack
    - _generated/images
  autoprefixer:
    browsers:
      - "last 10 versions"
      - "> 5%"
      - "IE > 8"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

  - scope:
      path: "projects"
      type: "posts"
    values:
      layout: "project"

  - scope:
      path: "blog"
      type: "posts"
    values:
      layout: "blog"
