partners:
  mary: 
    name: Mary Stufflebeam
    url: http://www.facebook.com/marystufflebeam/
  andre: 
    name: Andr&eacute; Crabb
    url: http://andrecrabb.com/
  hayg: 
    name: Hayg Astourian
    url: https://plus.google.com/118439878126727742596
  josh: 
    name: Joshua Hawn
    url: http://www.facebook.com/joshua.hawn

permalink: pretty
markdown: kramdown
kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: ''
    coderay_wrap: div
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
future: false
server: true
auto: true
